<template>
    <div class="col-md-12">
        <div class="panel panel-primary mb-3">
            <div class="panel-heading d-flex justify-content-between">
                <b>DETALLE DE EMBARGOS</b>
                <div class="d-flex align-items-center">
                    <b class="mr-2">PERIODO:</b>
                    <select class="form-control" @change="setSelectedPeriod($event.target.value)">
                        <option :value="period" v-for="period in embargosPeriodos" :key="period">
                            {{ period }}
                        </option>
                        <option v-if="isLoading" disabled>CARGANDO...</option>
                    </select>
                    <svg v-if="isLoading" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" width="41" height="41" style="shape-rendering: auto; display: block; background: transparent;" xmlns:xlink="http://www.w3.org/1999/xlink"><g><circle stroke-dasharray="169.64600329384882 58.548667764616276" r="36" stroke-width="10" stroke="#000000" fill="none" cy="50" cx="50">
                        <animateTransform keyTimes="0;1" values="0 50 50;360 50 50" dur="1s" repeatCount="indefinite" type="rotate" attributeName="transform"></animateTransform>
                        </circle><g></g></g><!-- [ldio] generated by https://loading.io -->
                    </svg>
                </div>
            </div>
            <div class="panel-body">
                <template v-if="embargosPerPeriod.items.length > 0">
                    <div class="row">
                        <div class="col-1">
                            <b class="panel-label table-text"></b>
                        </div>
                        <div class="col-3 px-0">
                            <b class="panel-label table-text">NOMBRE ENTIDAD ACTUAL:</b>
                        </div>
                        <div class="col-2 px-0">
                            <b class="panel-label table-text">NUMERO DE PAGARE:</b>
                        </div>
                        <div class="col-2 px-0">
                            <b class="panel-label table-text">CUOTA DEUDA:</b>
                        </div>
                        <div class="col-2 px-0">
                            <b class="panel-label table-text">FECHA INICIO DEUDA:</b>
                        </div>
                        <div class="col-2 px-0">
                            <b class="panel-label table-text">INCONSISTENCIA:</b>
                        </div>
                    </div>

                    <div
                        v-for="(item, key) in embargosPerPeriod.items"
                        :key="key"
                        class="row panel-br-light-green pt-3"
                    >
                        <div class="col-1 pr-0">
                            <b class="panel-label table-text"></b>
                        </div>
                        <div class="col-3 px-0">
                            <p>{{ item.entidaddeman || item.ndem || '-' }}</p>
                        </div>

                        <div class="col-2 px-0">
                            <p>{{ item.docdeman || item.iddem || '-' }}</p>
                        </div>

                        <div class="col-2 px-0">
                            <p>{{ (item.temb || item.valor || 0) | formatCurrency }}</p>
                        </div>

                        <div class="col-2 px-0">
                            <p>{{ item.fembini || '-' }}</p>
                        </div>

                        <div class="col-2 px-0">
                            <p>{{ item.motemb || '-' }}</p>
                        </div>
                    </div>
                </template>
                <p v-else-if="embargos.length == 0">El cliente no cuenta con embargos registrados.</p>
                <p v-else>No se encontraron embargos para el periodo seleccionado.</p>
            </div>
        </div>
    </div>
</template>

<script>
import { mapState, mapGetters, mapMutations } from 'vuex';

export default {
    name: 'Embargos',
    computed: {
        ...mapState('embargosModule', ['embargos']),
        ...mapGetters('embargosModule', ['embargosPeriodos', 'embargosPerPeriod']),
        isLoading() {
            console.log(this.embargosPeriodos)
            if(this.embargosPeriodos.length < 2){
                return true;
            }else{
                return false;
            }
        }
    },
    methods: {
        ...mapMutations('embargosModule', ['setSelectedPeriod'])
    },
    watch: {
        // Observa los cambios en embargosPerPeriod y muestra los datos en la consola
        embargosPerPeriod(newVal) {
            console.log('Listado de embargos:', newVal.items);
            // Aquí también puedes verificar si los valores están redondeados
            newVal.items.forEach(item => {
                console.log(
                    `Cuota de deuda (temb o valor) para ${item.docdeman || item.iddem}:`,
                    item.temb || item.valor
                );
            });
        }
    },
    filters: {
        formatCurrency(value) {
            if (isNaN(value)) return value;

            const parts = value.toString().split('.');

            parts[0] = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, '.');

            return '$' + parts.join(',');
        }
    }
};
</script>
