set -e

FILE="resources/assets/js/components/pages/ConsultDataClientDraft/EmploymentHistory.vue"
cp "$FILE" "$FILE.bak" 2>/dev/null || true

perl -0777 -i -pe 's/selectedPeriod\.len[a-zA-Z]*th/selectedPeriod.length/g' "$FILE"

perl -0777 -i -pe "s|(\\<script[^>]*\\>)|(\\1\nif (typeof window !== 'undefined') { console.log('[EmploymentHistory] script module loaded'); }\n)| unless /script module loaded/" "$FILE"

perl -0777 -i -pe "
  if (!/mounted\\s*\\(\\)\\s*\\{/) {
    s/(export\\s+default\\s*\\{)/\\1\\n  mounted() {\\n    try {\\n      const periodsLen = Array.isArray(this.pagaduriaPeriodos) ? this.pagaduriaPeriodos.length : 0;\\n      const couponsLen = (this.couponsIngresos && this.couponsIngresos.items) ? this.couponsIngresos.items.length : 0;\\n      console.log('[EmploymentHistory] mounted', { selectedPeriod: this.selectedPeriod, periodsLen, couponsLen });\\n    } catch(e) { console.log('[EmploymentHistory] mounted log error', e); }\\n\\n    if (!this.selectedPeriod || !this.selectedPeriod.length) {\\n      const fallback = (Array.isArray(this.pagaduriaPeriodos) && this.pagaduriaPeriodos.length) ? String(this.pagaduriaPeriodos[0]).slice(0,7) : new Date().toISOString().slice(0,7);\\n      if (typeof this.setSelectedPeriod === 'function') {\\n        this.setSelectedPeriod(fallback);\\n        console.log('[EmploymentHistory] mounted -> setSelectedPeriod', fallback);\\n      } else {\\n        this.selectedPeriod = fallback;\\n        console.log('[EmploymentHistory] mounted -> selectedPeriod asignado directo', fallback);\\n      }\\n    }\\n\\n    try {\\n      if (this.couponsIngresos && this.couponsIngresos.items) {\\n        this.arrayCoupons = [...this.couponsIngresos.items].map(c => {\\n          const raw = (c && c.dias_laborados) ? String(c.dias_laborados) : '';\\n          const m = raw.match(/\\d+/);\\n          return Object.assign({}, c, { dias_laborados: m ? m[0] : null });\\n        });\\n        console.log('[EmploymentHistory] mounted -> arrayCoupons', { len: this.arrayCoupons.length, sample: (this.arrayCoupons||[]).slice(0,3).map(x=>({code:x.code, dias_laborados:x.dias_laborados})) });\\n      } else {\\n        console.log('[EmploymentHistory] mounted -> no couponsIngresos.items');\\n      }\\n    } catch(e) { console.log('[EmploymentHistory] mounted arrayCoupons error', e); }\\n  },/;
  } else {
    s/(mounted\\s*\\(\\)\\s*\\{)/\\1\\n    try {\\n      const periodsLen = Array.isArray(this.pagaduriaPeriodos) ? this.pagaduriaPeriodos.length : 0;\\n      const couponsLen = (this.couponsIngresos && this.couponsIngresos.items) ? this.couponsIngresos.items.length : 0;\\n      console.log('[EmploymentHistory] mounted (inject)', { selectedPeriod: this.selectedPeriod, periodsLen, couponsLen });\\n    } catch(e) { console.log('[EmploymentHistory] mounted log error', e); }\\n\\n    if (!this.selectedPeriod || !this.selectedPeriod.length) {\\n      const fallback = (Array.isArray(this.pagaduriaPeriodos) && this.pagaduriaPeriodos.length) ? String(this.pagaduriaPeriodos[0]).slice(0,7) : new Date().toISOString().slice(0,7);\\n      if (typeof this.setSelectedPeriod === 'function') {\\n        this.setSelectedPeriod(fallback);\\n        console.log('[EmploymentHistory] mounted -> setSelectedPeriod', fallback);\\n      } else {\\n        this.selectedPeriod = fallback;\\n        console.log('[EmploymentHistory] mounted -> selectedPeriod asignado directo', fallback);\\n      }\\n    }\\n\\n    try {\\n      if (this.couponsIngresos && this.couponsIngresos.items) {\\n        this.arrayCoupons = [...this.couponsIngresos.items].map(c => {\\n          const raw = (c && c.dias_laborados) ? String(c.dias_laborados) : '';\\n          const m = raw.match(/\\d+/);\\n          return Object.assign({}, c, { dias_laborados: m ? m[0] : null });\\n        });\\n        console.log('[EmploymentHistory] mounted -> arrayCoupons', { len: this.arrayCoupons.length, sample: (this.arrayCoupons||[]).slice(0,3).map(x=>({code:x.code, dias_laborados:x.dias_laborados})) });\\n      } else {\\n        console.log('[EmploymentHistory] mounted -> no couponsIngresos.items');\\n      }\\n    } catch(e) { console.log('[EmploymentHistory] mounted arrayCoupons error', e); }\\n/;
  }
" "$FILE"

git add "$FILE"
git commit -m "chore(EmploymentHistory): logs en script y mounted, fallback de selectedPeriod y parsing de dias_laborados"
